### ISSUE TITLE
Simple Kerberos failed to load the "kerberos" module

### ISSUE THREAD

**Issue by Logeswaranbca** [noamokman/simple-kerberos#3]
I got the error to run node js file: 

Code 

`import simpleKerberos from 'simple-kerberos';`

Error : 
NestedError: Simple Kerberos failed to load the "kerberos" module
    at Object.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/simple-kerberos/lib/index.js:24:9)
    at Module.e (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:11532)
    at Q (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:186503)
    at /home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:188583
    at module.exports.r.a (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:188753)
    at Module._ (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:209303)
    at Module.d._compile (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:151591)
    at Object.f (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:209801)
    at Object.p (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:208903)
    at Object.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1:206275)
Caused By: /home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/simple-kerberos/node_modules/kerberos/lib/kerberos.js:1
Error: Cannot find module '../build/Release/kerberos'
    at /home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1
    at Proxy.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
    at /home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1
    at Proxy.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
    at Module.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
    at Module.t (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
    at x (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
    at Object.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/simple-kerberos/node_modules/kerberos/lib/kerberos.js:1)
    at Module.e (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
    at Q (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1) {
  nested: /home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/simple-kerberos/node_modules/kerberos/lib/kerberos.js:1
  Error: Cannot find module '../build/Release/kerberos'
      at /home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1
      at Proxy.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
      at /home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1
      at Proxy.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
      at Module.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
      at Module.t (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
      at x (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
      at Object.<anonymous> (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/simple-kerberos/node_modules/kerberos/lib/kerberos.js:1)
      at Module.e (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1)
      at Q (/home/hashprompt5/WORK.logeswarans/SSO/newLogin/node_modules/@std/esm/esm.js:1) {
    code: 'MODULE_NOT_FOUND',
    name: 'Error'
  },
  code: 'MODULE_NOT_FOUND',
  name: 'SimpleKerberosError'
}

**Comment by noamokman** [comment]
https://github.com/noamokman/simple-kerberos/blob/master/README.md#faq

**Comment by divyansh-gupta** [comment]
@noamokman the kerberos library is building and running for me, but I am still getting this error:

```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^
NestedError: Simple Kerberos failed to load the "kerberos" module
    at Object.<anonymous> (/home/admin@example.com/node-kerb/node_modules/simple-kerberos/lib/index.js:24:9)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/admin@example.com/node-kerb/node_modules/express-kerberos/lib/index.js:10:46)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
Caused By: TypeError: kerberosModule.Kerberos is not a constructor
    at Object.<anonymous> (/home/admin@example.com/node-kerb/node_modules/simple-kerberos/lib/index.js:22:14)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/admin@example.com/node-kerb/node_modules/express-kerberos/lib/index.js:10:46)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) {
  nested: TypeError: kerberosModule.Kerberos is not a constructor
      at Object.<anonymous> (/home/admin@example.com/node-kerb/node_modules/simple-kerberos/lib/index.js:22:14)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
      at Module.load (node:internal/modules/cjs/loader:972:32)
      at Function.Module._load (node:internal/modules/cjs/loader:813:14)
      at Module.require (node:internal/modules/cjs/loader:996:19)
      at require (node:internal/modules/cjs/helpers:92:18)
```
This is my package.json:
```
{
  "name": "kerb",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "composable-middleware": "^0.3.0",
    "express": "^4.17.2",
    "express-auth-negotiate": "^0.2.0",
    "express-kerberos": "^3.0.0",
    "kerberos": "^1.1.7",
    "lodash": "^4.17.21",
    "mockery": "^2.1.0",
    "simple-kerberos": "^3.0.0"
  }
}
```

Do you happen to know what could be going on here? Thank you!

**Comment by noamokman** [comment]
Sorry @divyansh-gupta, I no longer maintain this package, I think the api for the kerberos package changed.
I have no real way to test it so I no longer work on it, if you find a fix, feel free to submit a PR or fork the repo.
